# Generated by Django 5.1.6 on 2025-02-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
