# Generated by Django 5.1.6 on 2025-02-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_userinfo_age_userinfo_gender_userinfo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
