# Generated by Django 5.1.6 on 2025-02-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_alter_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
