# Generated by Django 5.1.6 on 2025-02-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0005_designation_userinfo_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='addDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
