# Generated by Django 5.1.6 on 2025-02-27 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
        ('userInfo', '0007_delete_adddesignation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designation.designation'),
        ),
        migrations.DeleteModel(
            name='designation',
        ),
    ]
