# Generated by Django 5.1.6 on 2025-02-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0002_alter_designation_designation'),
        ('userInfo', '0008_alter_userinfo_designation_delete_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='designation.designation'),
        ),
    ]
